### ISSUE TITLE
Remove darkness around edge.

### ISSUE THREAD

**Issue by harrisi** [harrisi/Console#17]
Treating the glyph as an alpha channel for a white image produces a better effect. Using duplicated information and glBlendEquation set to GL_MAX produces good results. Glyphs still have dark artifacts on some pixels which should be transparent and letting the background through. This is visible in other programs, such as PowerShell and Visual Studio 2017.

**Comment by harrisi** [comment]
I actually didn't notice the last comment before - @R030t1, are you saying that PowerShell and VS2017 and this project all show those artifacts?

**Comment by harrisi** [comment]
Also, this seems to almost contradict #15, or be a duplicate. These might be the same issue or have the same solution.

**Comment by R030t1** [comment]
>I actually didn't notice the last comment before - @R030t1, are you saying that PowerShell and VS2017 and this project all show those artifacts?

Yes, which might mean it can't be fixed (or at least it was hard enough to fix that the development teams for those pieces of software couldn't fix it).

#15 seems to have been already fixed - the black background was probably forgetting to enable alpha blending, but the thinness persists and is probably just how the font faces being tested are defined

**Comment by harrisi** [comment]
I can't seem to recreate the issue I had previously with a thin border around fonts. I'm not sure when that was fixed or if it is/was related to this. I also can't test the Windows behavior so I'll have to take your word for this being fixed.
