### ISSUE TITLE
Window size in pixels needs to be recovered from SDL_GL_GetDrawableSize as some OSes will hide high density display capability.

### ISSUE THREAD

**Issue by harrisi** [harrisi/Console#7]

**Comment by harrisi** [comment]
This seems to be a particular issue on devices running macOS Sierra (probably others) with a Retina™ display.

**Comment by harrisi** [comment]
15:57 < ianh> that was already handled, wasn't it?
15:58 < R0b0t1> Yeah

**Comment by R030t1** [comment]
This is fixed, but MacOS uses different font rendering settings than FreeType. Glyphs are slightly larger by default and almost bold due to antialiasing settings - both of which would appear to give the font face a blockier look which highlights the increased resolution of a Retina display.

**Comment by harrisi** [comment]
I'll be considering that a separate issue. Thanks.
